version: "2"

services:
  voting-app:
    image: olibob/votingapp_voting-app
    volumes:
     - ./voting-app:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier
    environment:
      - "constraint:node==mhs-dem3"

  result-app:
    image: olibob/votingapp_result-app
    volumes:
      - ./result-app:/app
    ports:
      - "5001:80"
    networks:
      - front-tier
      - back-tier
    environment:
      - "constraint:node==mhs-demo0"

  worker:
    image: manomarks/worker
    networks:
      - back-tier
    environment:
      - "constraint:node==mhs-demo0"

  redis:
    image: redis:alpine
    ports: ["6379"]
    networks:
      - back-tier
    environment:
      - "constraint:node==mhs-demo1"

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier
    environment:
      - "constraint:node==mhs-dem3"

volumes:
  db-data:

networks:
  front-tier:
    driver: overlay
  back-tier:
    driver: overlay
